name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository's code
      - name: Checkout code
        uses: actions/checkout@v3

      # List directory structure to verify correct path
      - name: List directory structure
        run: ls -R

      # Set up Node.js environment for React
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Optional: Start the Node.js server (only needed for testing or specific use cases)
      - name: Start Node.js server
        run: |
          npm start  # For running the app if it has a Node.js server or React server
        working-directory: ./  # Adjust this to your project directory if necessary
        continue-on-error: true  # Allow the workflow to continue even if this fails (optional)

      # Set up AWS CLI
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # List all S3 Buckets (optional, useful for debugging)
      - name: List all S3 Buckets
        run: |
          aws s3 ls

      # Ensure S3 Bucket Exists
      - name: Ensure S3 Bucket Exists
        run: |
          export BUCKET_NAME="react-s3-bucket"
          if ! aws s3 ls "s3://$BUCKET_NAME" 2>&1 | grep -q 'NoSuchBucket'; then
            echo "Bucket exists: $BUCKET_NAME"
          else
            echo "Bucket does not exist, creating: $BUCKET_NAME"
            aws s3 mb s3://$BUCKET_NAME
          fi
          echo "BUCKET_NAME=$BUCKET_NAME" >> $GITHUB_ENV

      # Upload a file to S3
      - name: Upload file to S3
        run: |
          echo "This is a sample file content" > index.js  # Create a sample file
          aws s3 cp index.js s3://$BUCKET_NAME/index.js  # Upload file to the bucket

      # Invalidate CloudFront cache (optional, if using CloudFront for caching)
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id your-cloudfront-id --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
