name: Deploy to GCS with HTTP

on:
  push:
    branches:
      - main

env:
  BUCKET_NAME: my-react-bckt
  PROJECT_ID: custom-unison-443618-h0

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build React app
      run: npm run build
      
    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ env.PROJECT_ID }}

    - name: Upload to GCS
      run: |
        gsutil -m rsync -r -d ./build gs://${{ env.BUCKET_NAME }}

    - name: Set Cache-Control
      run: |
        gsutil -m setmeta -h "Cache-Control:public, max-age=3600" gs://${{ env.BUCKET_NAME }}/**/*.html
        gsutil -m setmeta -h "Cache-Control:public, max-age=31536000" gs://${{ env.BUCKET_NAME }}/**/*.{css,js,jpg,jpeg,png,gif}
